### ISSUE TITLE
Review Roadmap

### ISSUE THREAD

**Issue by nopara73** [nopara73/MagicalCryptoWallet#1]
Just skim it through, and say "Go, No-Go" or to modify something.
https://github.com/nopara73/MagicalCryptoWallet/blob/master/README.md

**Comment by lontivero** [comment]
I've readed it. We could split the roadmap in stages or plan some important milestones, for example: 

- *Stage 1:* codename: ??? - point's 1, 2, 3 and 4. 
- *Stage 2:* codename: ??? - point's 5, 6, 7, 8 and 9.
- *Stage 3:* codename: ??? - point's 10, 11 and 12.

**Comment by nopara73** [comment]
Good idea. I think it should be 4 stage: wallet, mixing, UX, deployment.

- *Stage 1:* codename: ??? - point's 1, 2, 3 and 4. 
- *Stage 2:* codename: ??? - point's 5, 6, and 7.
- *Stage 3:* codename: ??? - point 8.
- *Stage 3:* codename: ??? - point's 9, 10, 11 and 12.

Still missing codenames.
