### ISSUE TITLE
Improve naive exchange rate query

### ISSUE THREAD

**Issue by nopara73** [nopara73/MagicalCryptoWallet#11]
Backend answers for exchange rates in a naive way.   

Function to improve: `BlockchainController.GetExchangeRatesAsync`.  

Outline of performance increases:  

```cs
// ToDo: Implement caching for instant answers.
// ToDo: Implement redundancy, call another API if SmartBit fails, if that fails, call another one.
```

**Comment by lontivero** [comment]
Solved in https://github.com/nopara73/MagicalCryptoWallet/pull/31 pull request.
