### ISSUE TITLE
Make sure MemPoolService.TransactionHashes don't overflow

### ISSUE THREAD

**Issue by nopara73** [nopara73/MagicalCryptoWallet#19]
In MemPoolBehavior:

```cs
foreach (var inv in invPayload.Inventory.Where(inv => inv.Type.HasFlag(InventoryType.MSG_TX)))
{
	// if we already have it continue;
	// ToDo: Make sure TransactionHashes don't overflow
	if(!MemPoolService.TransactionHashes.Add(inv.Hash))
	{
		continue;
	}

	payload.Inventory.Add(inv);
}
```

**Comment by lontivero** [comment]
## Trying to get an OverflowException with brute force

I wasn't able to make it overflow, in fact it freezes my machine after 50,000,000 of UInt256 instances. In my machine (w/ 8GBs RAM) the test below can add successfully 40,000,000 of UInt256.

<details><summary>C# Demo Code</summary>

```c#
using System;
using System.Threading.Tasks;
using ConcurrentCollections;
using NBitcoin;

namespace test_mempool
{
    class Program
    {
        static void Main(string[] args)
        {
            var hashes = new ConcurrentHashSet<uint256>();
            var count = 0UL;

            while(count < 40*1000*1000)
            {
                var hash = new uint256(++count);
                try{
                    if(count % 100000==0){
                        Console.WriteLine($"{count} items");
                    }
                    if(!hashes.Add(hash))
                    {
                        Console.WriteLine("Failed!");
                        break;
                    }
                    }catch{
                        break;
                    }
            }
            Console.WriteLine($"Capacity = {hashes.Count}");
        }
    }
}

```
</details>

## Code review

Checking the code of the ConcurrentHashSet class I can see that it can only overflow in [this line](https://github.com/i3arnon/ConcurrentHashSet/blob/master/src/ConcurrentHashSet/ConcurrentHashSet.cs#L645) so, it can overflow when there is 2,147,483,648 in one. We will run out of memory before our mempool reaches that amount of transaction hashes.

## Other considerations

The following is just an imaginary situation:
Given an average transaction of 500 bytes (currently is much bigger) and a maximun blocksize of 4mb (currently we dont have this) we could have 8,000 transaction per block (one each 10 minutes in average). Considering that in my 8gb ram machine it was able to store 40,000,000 transaction hashes then, that could be enough for keeping transaction hashes for 500 blocks (3.4 days more or less) without flushing the hashset. Clearly, under real conditions it can keep the hashset many many more time.

## Conclusion

It is almost impossible to make it overflow.

**Comment by nopara73** [comment]
You're overkilling it:) Removed ToDo comment: https://github.com/nopara73/MagicalCryptoWallet/commit/83be736126e6602dba25f5702eb0465d2e3b617a
