### ISSUE TITLE
CI badges show failing when another branch failed.

### ISSUE THREAD

**Issue by nopara73** [nopara73/MagicalCryptoWallet#27]
@lontivero Could you create new branches with the traditional upstream-origin GitHub way? Right now you are working inside my repository, since you have a commit access. No worry about the existing branches, just keep in mind for new ones, ok?

**Comment by lontivero** [comment]
ack

**Comment by nopara73** [comment]
@lontivero You don't need to reject the failing PR-s, the PR-s are not a problem, the failing branches I believe.  
But as I said, don't worry about it now, it's rather to be a future policy, and don't remove your current branches here for the shake of administration, keep working on them, but when you would create a new branch in the future, create it under your name and use this as an upstream.
