### ISSUE TITLE
What is `waitforblock`?

### ISSUE THREAD

**Issue by nopara73** [nopara73/MagicalCryptoWallet#32]
https://twitter.com/nopara73/status/968381548310429696

@lontivero Could you take a quick look into this? I've never heard of it. It may be simpler than the notification script we are using.

**Comment by lontivero** [comment]
I'm on that

**Comment by lontivero** [comment]
`waitforblock` is a RPC procedure that receives a blockhash and an optional timeout parameter and returns once that specific blocks has arrived. It is specially useful for being notified when the synchronization process is in a well-known point.

`ẁaitfornewblock` is another RPC call that waits for a new block and response when a new block arrives. This is the one that can be used in replace of the `blocknotify`.

`waitforblockheight` is another useful RPC procedure that we should take into account. The name is clear.  

The code for this three RPCs starts here: https://github.com/bitcoin/bitcoin/blob/228b086b9a3de02b534474027353a80dead2c292/src/rpc/blockchain.cpp#L205

**Comment by nopara73** [comment]
Hmm, not sure if we should use this. Reorgs seems to be difficult. What happens at reorg?  
Eg. `waitfornewblock` got a block. Then issue `waitfornewblock` again, then reorg.  
Is it going to push us the reorg blocks?

**Comment by lontivero** [comment]
The worst thing that can happen is that we create a filter for orphan blocks. I don't see a problem here.

**Comment by nopara73** [comment]
The problem is how do you detect reorgs?  
After every waitfornewblock you'll issue new getheader RPC command?

**Comment by nopara73** [comment]
Also what if you miss a block for some strange reason.

**Comment by nopara73** [comment]
However the prevhash is referenced in the header, so we should be able to figure out if we get the right block or have to query backwards. Indeed it's a workable solution.
