### ISSUE TITLE
Add `waitforblock` to Golomb-Rice filtering PR

### ISSUE THREAD

**Issue by nopara73** [nopara73/MagicalCryptoWallet#40]
https://github.com/nopara73/MagicalCryptoWallet/pull/38

Right now, I'm just periodically asking for block from the RPC, and if the block height doesn't exist, then I wait 1 sec and continue. With waitforblock it'd be more elegant.

Current code:  

```cs
Block block = null;
try
{
	block = await RpcClient.GetBlockAsync(height);
}
catch (RPCException) // if the block didn't come yet
{
	// ToDO: If this happens, we should do `waitforblock` RPC instead of periodically asking.
	// In that case we must also make sure the correct error message comes.
	await Task.Delay(1000);
	continue;
}
```

**Comment by lontivero** [comment]
The Bitcoin Core team has [removed the RPC  `waitforblock` and `waitfornewblock` procedures](https://github.com/bitcoin/bitcoin/pull/10519) a few hours ago. I pushed a [PR for NBitcoin with these RPC methods](https://github.com/MetacoSA/NBitcoin/pull/363) and @NicolasDorier let me know the methods won't be available in coming releases.

We need to change the plan and go back to the first idea of using `notifyblock` with `curl` or move foward with the current pulling mechanism.

**Comment by NicolasDorier** [comment]
I think you should take a look to https://github.com/dgarage/NBXplorer/blob/master/docs/API.md

**Comment by lontivero** [comment]
Sure, I've read on twitter about the painful points that drove you to avoid RPC and base NBXplorer on the P2P protocol. I think that the power to subscribe and get notifications via websocket is awesome. But I am not sure that's enough for adding a new component to this design. @nopara73, what do you think?

**Comment by NicolasDorier** [comment]
The nuget package is `NBxplorer.Client` also, quite easy to use.

**Comment by nopara73** [comment]
> The Bitcoin Core team has removed the RPC waitforblock and waitfornewblock procedures a few hours ago.

It didn't removed it. The PR is open.

> We need to change the plan and go back to the first idea of using notifyblock with curl or move forward with the current pulling mechanism.

Let's keep it as it is for now. All other ways doing this is a big hack. Let's see what happens with the PR, if it get merged then we reconsider it.

> But I am not sure that's enough for adding a new component to this design. @nopara73, what do you think?

I believe stability and good documentation is more important for us, than flexibility. At least for now.

**Comment by NicolasDorier** [comment]
> It didn't removed it. The PR is open.

I was in a core dev meeting in NYC these past 3 days. They were discussing it and it is coming... :/

**Comment by lontivero** [comment]
Just in case, I've pushed a PR adding these methods to the project here: https://github.com/nopara73/MagicalCryptoWallet/pull/65

**Comment by nopara73** [comment]
@NicolasDorier Ahh, that's from 2016. Life is too short to work on something that has less than 1% chance of succeeding 😄

**Comment by nopara73** [comment]
Here's the compromise: https://github.com/nopara73/MagicalCryptoWallet/pull/65

We merged an RPC extension, but don't use it. Closing this issue.
