### ISSUE TITLE
CryptographicException ruining the Debug log

### ISSUE THREAD

**Issue by nopara73** [nopara73/MagicalCryptoWallet#54]
@lontivero In the `AuthenticateMessageTest` there is 10000 of this message if you run the tests in debug mode in Visual Studio: `Exception thrown: 'System.Security.Cryptography.CryptographicException' in MagicalCryptoWallet.dll`.  

Is there any way to make it not write the exception to Debug output that without turning off the test?  
If there is no, I think we should lower the cycle to run 3 times only.

**Comment by lontivero** [comment]
If you use Visual Studio I'm pretty sure you can specify what information you what to see and what you don't. In Visual Studio Code i'm not so sure.

**Comment by nopara73** [comment]
It's an exception thrown by a dll, which I usually want to see in the debug log, but not in this case, at least not 10000 times. Never mind, I lowered the number of times this test to run.
