### ISSUE TITLE
Add Guard.Correct pattern

### ISSUE THREAD

**Issue by nopara73** [nopara73/MagicalCryptoWallet#71]
It's a straightforward improvement I believe.

https://github.com/nopara73/MagicalCryptoWallet/blob/b268cb3236718c462a027617cc65ed8757675258/MagicalCryptoWallet/Services/WalletService.cs#L178-L201

**Comment by lontivero** [comment]
Pushed directly because it is a trivial change. commit 612e6aa7d951dfca3cda2787536ad3355ce0f234
