### ISSUE TITLE
Add functionalities and xml comments to Height struct

### ISSUE THREAD

**Issue by nopara73** [nopara73/MagicalCryptoWallet#72]
Functionalities:
  Increment
  Decrement
  operator +
  operator -

And basically any operator that you can figure and makes sense.

For this you must understand the Height struct. You may want to start with the xml comments, that helps you in the understanding. It's a quite handy class. It's basically an int, plus it has two special values: `Height.Unknown` and `Height.Mempool`

**Comment by lontivero** [comment]
Implemented by **Height comments** PR #83
