### ISSUE TITLE
Add RPCs to NBitcoin

### ISSUE THREAD

**Issue by nopara73** [nopara73/MagicalCryptoWallet#73]
Go through what RPC-s are used in the tesoftware and if the RPC is used manually with `SendCommandAsync`, then implement and add them to NBitcoin. Try doing full job, ergo don't do things, like throwing away an RPC response, because that doesn't seem relevant.

Also add tests.

**Comment by lontivero** [comment]
I've added `getblockchaininfo`, `bumpfee`, and have modified the `sendtoaddress` to allow RBF. The PR is: https://github.com/MetacoSA/NBitcoin/pull/377
