### ISSUE TITLE
Add OSX and Linux CI to NBitcoin

### ISSUE THREAD

**Issue by nopara73** [nopara73/MagicalCryptoWallet#74]
It'd be really good if CI would be done on different platforms in NBitcoin. I'm afraid, there'd be some really nasty issues and it'd take a lot of time, I'm not sure it worth it. Maybe try spending 3 days on it and if the tests still don't pass, then leave it?

**Comment by lontivero** [comment]
I was reading about the [new AppVeyor build worker for Linux](https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/#introduction) but sadly it is only for private beta testers.

> Running your build on Linux
>
>> AppVeyor for Linux is currently in private beta. Both paid and free AppVeyor accounts are entitled to participate in the beta. Please contact us by email or post a message on forums to enable Linux image for your account. 

Anyway, I sent them and email asking to be added as beta testers (you, me and Nicolas). Now we jast need to wait.

I' going to try with travis now.

**Comment by nopara73** [comment]
I don't think using a beta is a good idea anyway.

**Comment by lontivero** [comment]
Done. Except for the tests that require the consensus library
