### ISSUE TITLE
Use new NBitcoin PRCs

### ISSUE THREAD

**Issue by nopara73** [nopara73/MagicalCryptoWallet#79]
https://github.com/nopara73/MagicalCryptoWallet/issues/73

https://github.com/MetacoSA/NBitcoin/pull/377

**Comment by lontivero** [comment]
I've asked Nicolas Dorier (by Gitter) if he has a estimated date for releasing a version with those new RPC methods. He uses to release quite often so I hope we have a new NBitcoin package for this week or so.
